### ISSUE TITLE
When will LE 23.1.2.5 drop publicly?

### ISSUE THREAD

**Issue by Alvinnoga2** [xAranaktu/FIFA-23-Live-Editor#121]

**Comment by xAranaktu** [comment]
Apr 26, 2023 at 3:10 PM CET

**Comment by Alvinnoga2** [comment]
> Apr 26, 2023 at 3:10 PM CET

The time has passed when will it drop

**Comment by xAranaktu** [comment]
The dates I give are always referring to the posts on Patreon page because there I can set when the post automatically will unlock for everyone. On GitHub releases I need to drop the files manually, so it's usually delayed by day or two.

[v23.1.2.5 GitHub release](https://github.com/xAranaktu/FIFA-23-Live-Editor/releases/tag/v23.1.2.5)
