### ISSUE TITLE
My live editor launcher is not "launching"

### ISSUE THREAD

**Issue by jpmachadoo** [xAranaktu/FIFA-23-Live-Editor#166]
Already tried 6 different releases of it and the same problem happens. I run the fake anti cheat and it's all good, but when i try to execute the launcher nothing happens, literally nothing. Feels like windows is trying to run the .exe file but it's empty, it's like i never clicked on it.
Is there any related issues? I can record my screen to show the problem as well

**Comment by xAranaktu** [comment]
send log files

**Comment by jpmachadoo** [comment]
oh and i tried cleaning the registry just like mentioned in the related issue that Sparrow75 opened and i didnt work out.
There's only english characters in my folder's path as well,

**Comment by thekupon23** [comment]
I found a way to fix it so that liveeditor starts!
Logs helped me (as xAranaktu wrote)
I once deleted the locale.ini file (for sponsors)
and in the logs I saw that the liveeditor swears that there is no this file, so I returned it back to the folder with the game and Hooray! liveeditor HAS STARTED)))

here's what they wrote to me in the logs: [18:34:28.502] [WARN] [UIWindows::UILocaleIni::Init] Can't find D:\FIFA 23\Data\locale.ini

from Russia with love )



> о, и я попытался очистить реестр, как упоминалось в связанной проблеме, которую открыл Sparrow75, и у меня ничего не вышло. В пути к моей папке также есть только английские символы,

**Comment by jpmachadoo** [comment]
thanks for the reply @thekupon23, i really appreciate it!
my locale.ini file is in the right place so i don't think i'm having the same problem. Where can i find the logs? i have no idea where to search it
