### ISSUE TITLE
Player height field max value too low (220) - Should be 257

### ISSUE THREAD

**Issue by earomc** [xAranaktu/FIFA-23-Live-Editor#168]
When I try to set a player's height with this lua code (snippet):
```
player.height.value = tostring(256)
EditDBTableField(player.height)
```
I get this error message:

`[22:22:47.465] [33592] [ERROR] [LE::Table::FieldDescription::IsIntValid] 256 is too high for height field. Max valid value is: 220`

However the same code worked with values below or equal to 220
The problem is, the max value for height cannot be 220. With the Cheat Table Player Editor, the highest I could set it to was exactly **257**. 
The lua API or whatever is throwing this error message should only throw it when the value is above 257

**Comment by xAranaktu** [comment]
In FIFA Database every single bit matter. If you will force higher value than allowed then you will overwrite data that is stored after height which is easy method to break your save.
But yes, indeed there is some space to set the player height up to 257.

`db_meta.xml` must be changed before you start the live editor and the game. Maybe you didn't saved the file or idk.
I've tried by myself and it worked.

![](https://i.imgur.com/WLaTnZj.png)
![](https://i.imgur.com/MzVDFGT.png)

**Alsowhy can I set players to 220cm with a script, but only to 215cm in the LE Player Editor? There definitely are some inconsistencies regarding what height can be set.** 

Height has custom mapping stored in `C:\FIFA 23 Live Editor\data\id_map.json` file
![](https://i.imgur.com/mb25iWE.png). 
You can add your own values there for height (but still you won't be able to use higher values than 220 if you won't edit the `db_meta.xml`)
Before FIFA 23 the max value for height was 215cm. I didn't updated the `id_map.json` and that's why it's still 215 there, I didn't even knew that EA has increased that value.

**Comment by earomc** [comment]
Hey first of all thanks for the detailed answer!
I found out that there were 11 hits for "height" fields in my text editor when I searched for it and I replaced the wrong height field in the wrong table ... that was my bad. It works now!
Now I'm asking myself: Wouldn't it be a good idea to make 257 the default in the db_meta.xml file for height? Or would that be a risk/vulnarability of some sort?

**Comment by xAranaktu** [comment]
The only risk is that you may break your career save. At first glance as I said it looks safe to do, but you never know...
