### ISSUE TITLE
is my account banned?

### ISSUE THREAD

**Issue by Farrelstoff** [xAranaktu/FIFA-23-Live-Editor#202]
![2C690A09-05FA-4DC8-A80F-45722BFDC102](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/137461938/6c4eeba1-bd74-4882-9a77-fbe8780e871b)

**Comment by Farrelstoff** [comment]
everything i have done. I tried reinstalling FIFA 23 but it still crashes when I enter gameplay. I've also tried running fifa 23 without mods but it's the same. i hope you can help me in this matter.

**Comment by xAranaktu** [comment]
You should get emailed if your account got banned. If you don't have any email then I don't think it's a ban.
Crash can be caused by mods.
To run the game without mods you need to remove `-dataPath FIFAModData` from `Advanced Launch Option`
![](https://camo.githubusercontent.com/2ae6c7b898caaf58881b5e7d46125a6ac179e4a1513047ebdc2c79436f8ee3df/68747470733a2f2f692e696d6775722e636f6d2f6c33724b5430552e706e67)

If it's not mod manager then still it can be the squadfile you used that's causing this or the things that you edited before.
You should do clean game reinstall, download latest & original squad files and start new career

**Comment by Farrelstoff** [comment]
i have tried everything. but still the same. and now i cant play fifa 23
