### ISSUE TITLE
Only run in task manager

### ISSUE THREAD

**Issue by zidraf123** [xAranaktu/FIFA-23-Live-Editor#281]
everything works perfectly, but the game only open inside task manager

**Comment by GamersBros** [comment]
same problem

**Comment by xAranaktu** [comment]
Live Editor doesn't work with Title Update 15. You need to wait for new version.

**Comment by xAranaktu** [comment]
> any idea when you make a new one??

[FIFA 23 Live Editor v23.1.3.3](https://www.patreon.com/posts/86334473)

Public release on:
Jul 26, 2023 at 3:30 PM CEST

**Comment by Jayden0907** [comment]
Can you really not release it earlier?

**Comment by xAranaktu** [comment]
> Can you really not release it earlier?

Can you stop updating your game if you know that there will be troubles with launching LE after you do that?

**Comment by idlans** [comment]
> 

its hard i dont have cc and paypal and its cannot buy with another digital payment in my country indonesian

**Comment by Jayden0907** [comment]
@xAranaktu 
Is there any way to play an older version of fifa 23 via Steam?

**Comment by xAranaktu** [comment]
> So I don't know what he is talking about, by not updating game.

On EA App you turn off auto updates and go offline on the app. You can start the game without updating. I don't have the game on Steam, but I don't believe that running the steam in offline mode also will prevent you from playing the game. 
Yes, after a while Denuvo may force you to renew the validation key, that's why you should have copy of the files.
Since FIFA 21 I'm regulary swtiching between game versions and I never had problems with it. I've described how I'm doing it [here](https://github.com/xAranaktu/FIFA-23-Live-Editor/wiki/Game-Backup)

**Comment by erald2** [comment]
same problem ,the game only open inside task manager

**Comment by joeysaladt** [comment]
how do u launch inside of task manager?

**Comment by SanderVincenzoO** [comment]
se eu assinar o mensal, consigo acessar o Live editor v23.1.3.3 - vai rodar normal no meu fifa?

**Comment by helmettolga** [comment]
Can you release the new version?
