### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by francoism90** [xAranaktu/FIFA-23-Live-Editor#8]
I'm trying to get FIFA 23 to work under Linux, so far this is the progress:

![Screenshot from 2022-11-08 20-52-09](https://user-images.githubusercontent.com/5028905/200661618-531415f2-e0aa-4c9b-8a2c-e92ad1ffb6f6.png)

I'm using your modified `EAAntiCheat.GameServiceLauncher.exe`, which seems to bypass the 'Wine is not support' message and I got it launched! It doesn't seem to load/hang, eventually it crashes.

Could you please give me more details? Maybe by e-mail/DM/Discord? I think you're pretty close, it would be great news for Steamdeck users!

Thanks!

**Comment by xAranaktu** [comment]
My modified `EAAntiCheat.GameServiceLauncher.exe` isn't doing anything special. Its code you can find [here](https://pastebin.com/raw/0egrWbq0). 
EA also protected the game client, otherwise the whole anticheat wouldn't make sense as there is multiple ways to run the game without the EAAC launcher. If you want to play without the anticheat you need to also modify the game client. I can't say what I've done exactly to accomplish that for various reason. I can't help you, sorry.

**Comment by francoism90** [comment]
@xAranaktu Thanks for your detailed answer and sharing the code.

I do understand not wanted to share more details and you need to be careful, so no worries. :)

It seems it only launches when using [FMT](https://github.com/paulov-t/FrostbiteModdingTool), I'll take a look, it seems Linux support is included in FIFA 23, but only disabled by EAAC.
