### ISSUE TITLE
Lua engine error - CreatePlayer

### ISSUE THREAD

**Issue by OfficialTomPG** [xAranaktu/FIFA-23-Live-Editor#80]
When trying to use the CreatePlayer function in the LUA Engine, the following error appears when using the code provided on the Wiki page:

[ERROR] [LE::Table::FieldDescription::IsIntValid] 2147483647 is too high for artificialkey field. Max valid value is: 300000

I have tried appending the line `artificialkey = "299999"` to the `player_data` but this doesn't work. Script says it completes successfully but it does not create the player.

**Comment by xAranaktu** [comment]
You are using the exact same code that's on Wiki without any changes? For me it's working fine. So, the function is working.
Are you using any mods? `artificialkey` is field in `teamplayerlinks` table, the code probably fails then trying to "transfer" the player to free agents. Without seeing your career/squad file my quess is that it doesn't work because your `teamplayerlinks` is full.

**Comment by xAranaktu** [comment]
Oh, sorry. I've tried again and this time didn't worked. I think I know what's wrong. Will try to fix that in next update.

**Comment by OfficialTomPG** [comment]
Thanks for looking into this so quick! Glad to hear that it is re-creatable and will be looked into! Keep up the great work!
