### ISSUE TITLE
Live Editor Failed

### ISSUE THREAD

**Issue by YGTKMN** [xAranaktu/FIFA-23-Live-Editor#84]

**Comment by YGTKMN** [comment]
No game found after 1200 attempts 
PID:11836 ERRORR INJECTOR::DOLNJECTDLL OPENPROCESS FAİLED  ACCESS DENIED(5)
PID:15112 STATUS: OK

**Comment by Morphy9gg** [comment]
> 

Yes bro, I am also having the same problem, Live Editor will work if we delete (-dataPath FIFAModData) but if we do, the mod won't work at all

**Comment by YGTKMN** [comment]
i don't understand bro dude what should i delete or install.I don't use any mods other than Live Editor.

**Comment by Morphy9gg** [comment]
> saya tidak mengerti bro bung apa yang harus saya hapus atau instal. Saya tidak menggunakan mod apa pun selain Live Editor.

i had this after TU9

**Comment by YGTKMN** [comment]
my problem still persists and i am waiting for aranaktu to update faster now

**Comment by YGTKMN** [comment]
What is TU9 ? I dont Understand

**Comment by Morphy9gg** [comment]
now is working bro

> Tidak ada yang diperbarui karena Live Editor berfungsi dengan baik di TU9.

**Comment by YGTKMN** [comment]
> şimdi çalışıyor kardeşim
> 
> > TU9'da Canlı Editör'ü kullanmak için birkaç adım var.

paylaştığın içeriğe nasıl ulaşabilirim ?

**Comment by JoaoSudre** [comment]
I have the same error, no one found a solution

**Comment by karlkarltong** [comment]
> No game found after 1200 attempts
> PID:11836 ERRORR INJECTOR::DOLNJECTDLL OPENPROCESS FAİLED ACCESS DENIED(5)
> PID:15112 STATUS: OK

Same error here after update TU9, and no solution from now.

**Comment by karlkarltong** [comment]
tried the most new version 23.1.2.1 of LE still no luck.

**Comment by karlkarltong** [comment]
It was something weird, i tested on my another pc with windows 11 it still works normally with LE after update TU9.

But, on my steam deck with windows 11 it got this error.

So, on different pc will get different result.

**Comment by xAranaktu** [comment]
I'm not able to reproduce the "OPENPROCESS  access denied error", so I don't think there won't be any fix for that

**Comment by karlkarltong** [comment]
> I'm not able to reproduce the "OPENPROCESS access denied error", so I don't think there won't be any fix for that

any method do you suggest so i can try it?

**Comment by Morphy9gg** [comment]
I have a solution for this, steps :
1. open LE as usual, and run the game
2. Close LE and EA Apps (if you use them)
3. open LE again
4. Make sure you are still in the LE menu (don't open the game yet)
5. click in the upper left corner, the windows section, you can click the "info" chart then click anywhere in the LE menu, then open the windows section again, and click the checklist again in the info section
5. Run the game, good luck

**Comment by tsuruhime** [comment]
> I have a solution for this, steps :
> 
> 1. open LE as usual, and run the game
> 2. Close LE and EA Apps (if you use them)
> 3. open LE again
> 4. Make sure you are still in the LE menu (don't open the game yet)
> 5. click in the upper left corner, the windows section, you can click the "info" chart then click anywhere in the LE menu, then open the windows section again, and click the checklist again in the info section
> 6. Run the game, good luck

still cant

**Comment by xAranaktu** [comment]
> > I'm not able to reproduce the "OPENPROCESS access denied error", so I don't think there won't be any fix for that
> 
> any method do you suggest so i can try it?


Potential solutions:
- Go Online on EA App (this is required for first run)
- Change injection delay
- Run game without mods and without advanced launch options (like `-dataPath FIFAModData`)
- <https://windowsreport.com/createprocess-failed-code-740/> (+ what you can find in google when you search for `CreateProcess error 740`)
- Move the live editor to the folder with the game
- Make sure the windows user that you are currently logged in on has full admin rights. 
- Change game installation directory to somewhere that doesn't require admin rights
- Go to your game installation dir -> FIFA23.exe -> Properties -> Compatibility and uncheck "Run as Administrator" 
- Make sure your antivirus isn't a problem
- Try to start live editor launcher and then instead of pressing "run game" button start the game from EA App

**Comment by Abacuzzz** [comment]
Hi @xAranaktu 
Please there is a bug with player hands when you import edited player text into RDBM 23 after TU9.

**Comment by Morphy9gg** [comment]
> I have a solution for this, steps :
> 
> 1. open LE as usual, and run the game
> 2. Close LE and EA Apps (if you use them)
> 3. open LE again
> 4. Make sure you are still in the LE menu (don't open the game yet)
> 5. click in the upper left corner, the windows section, you can click the "info" chart then click anywhere in the LE menu, then open the windows section again, and click the checklist again in the info section
> 6. Run the game, good luck

Hi @xAranaktu , I have succeeded in this way, but when I want to add a miniface (in the player menu) the application instead force closes

**Comment by maxdlpee** [comment]
So you'll just write ALL these complaints off as "user error"? ALL OF THESE?
Some devs you are, not even trying to see what's wrong, because "iT wOrKs on my mAchiNe, so all tHeSe guYs mUst be tRollS or sOmEthiNg"

**Comment by dan-457** [comment]
Just wanted to add, this is occurring for me after the TU9 update. Before that, I had no issues running the Live Editor at all for weeks. In fact, I was using it literally every time I played game.

A few days ago I was actually using the Live Editor when it crashed FIFA, and as I was about to restart the game, Steam took the opportunity to update to TU9. Since then LE will not function at all, no matter what I try. I had assumed that the update made it incompatible, but it appears that's not entirely the case given by some of the above comments. I've tried every kind of permissions change I can think of (changing owner/ granting full access), adding exceptions/disabling AV, verifying files and moving the games install directory altogether, deleting appdata files, reinstalling EA play, etc. I'm also not currently using any mods, so no conflicts there.

Is it possible this is limited to those who use the steam version of the game? It's just strange that it was working perfectly and then a few minutes later not at all (not even an exaggeration) if its not related to the update.

**Comment by maxdlpee** [comment]
It could be a possibility that this is a Steam-only issue, as I'm using it as well. I'm reinstalling the game rn and I'll comment if that solved it or not.

**Comment by karlkarltong** [comment]
I have tried to uninstall steam, LE and fifa23, then reinstalled. But still no luck and also same error appeared.

**Comment by karlkarltong** [comment]
Nice! problem solved by LE v23.1.2.2

**Comment by SR1D** [comment]
has anyone found a solution???

**Comment by maxdlpee** [comment]
Please read the message above you

**Comment by Nimbip** [comment]
![image](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/138609667/c56c0b39-ea2b-4dc0-8075-2c686e5873ff)
i'm having this issue rn with live editor and couldn't found any solution yet, can anyone help?

**Comment by AdaFizz** [comment]
![image](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/141221647/982b35f8-1cf3-44ba-b613-0d5a902c510d)

**Comment by AdaFizz** [comment]
![image](https://github.com/xAranaktu/FIFA-23-Live-Editor/assets/141221647/a32d8113-eaba-46ac-97d7-d2020874118f)
 i am having this issue when i want start the launcher

**Comment by Bubbalu022** [comment]
Anyone found a solution for this? i have the same problem
